apiVersion: v1
kind: Service
metadata:
  name: pma-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
  labels:
    app: pma
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 5000
  selector:
    app: pma
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pma-deployment
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - image: pma_image
        name: pma
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: pma