apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
  labels:
    app: wordpress
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 5050
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress_image
        name: wordpress
        imagePullPolicy: Never
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-svc
        - name: WORDPRESS_DB_PASSWORD
          value: admin
        ports:
        - containerPort: 5050
          name: wordpress