apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 20
      protocol: TCP
      name: connection
    - port: 21
      protocol: TCP
      name: transfer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21